class Solution:
    def combinationSum2(self, candidates: List[int], target: int) -> List[List[int]]:
        
        ans = []
        perm = []
        candidates.sort()

        def dfs(idx, left_over):

            if left_over == 0:
                ans.append(perm[:])
                return

            if left_over < 0 or idx == len(candidates):
                return 
   
            # take
            perm.append(candidates[idx])
            dfs(idx + 1, left_over - candidates[idx])
            perm.pop()
            
            # Since nums is sorted, duplicates are adjacent.
            # We already included nums[idx] in the "take" path above.
            # In the next stage, we will again have "take" and "not take" paths for nums[idx + 1].
            # If nums[idx + 1] is the same value, taking it would generate subsets that were already
            # generated by the "take" path for nums[idx]. Therefore, skip all consecutive duplicates
            # before exploring the "not take" path.
            while idx < len(candidates) - 1 and candidates[idx] == candidates[idx + 1]:
                idx += 1

            # not take
            dfs(idx + 1, left_over)


        dfs(0, target)

        return ans