class Solution:
    def subsetsWithDup(self, nums: List[int]) -> List[List[int]]:
        
        # TC: O(n · 2ⁿ)
        # SC: O(n · 2ⁿ)

        ans = []
        perm = []
        nums.sort()

        def dfs(idx):

            if idx == len(nums):
                ans.append(perm[:])
                return

            # take
            perm.append(nums[idx])
            dfs(idx + 1)
            perm.pop()
            
            # Since nums is sorted, duplicates are adjacent.
            # We already included nums[idx] in the "take" path above.
            # In the next stage, we will again have "take" and "not take" paths for nums[idx + 1].
            # If nums[idx + 1] is the same value, taking it would generate subsets that were already
            # generated by the "take" path for nums[idx]. Therefore, skip all consecutive duplicates
            # before exploring the "not take" path.
            while idx < len(nums) - 1 and nums[idx] == nums[idx + 1]:
                idx += 1

            # not take
            dfs(idx + 1)


        dfs(0)


        return ans
